# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f10b3a7c1a22580cbf1630a7a85a0dc395b3ce9396e817da62e9a35cfb725a37874b756c362bee00e7665ad80a07b772e4816302e2caccfa57089df16c29ea86

test:
  secret_key_base: 746043e99c548c21d20c6aa8f0e2f4e4ee25b0b432d1609534b9ae8ad79e697fc89fb93e7943da27e347862543aeacb90d6196382d3c512c8b4c6f296e30789b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
